### PR TITLE
Add time limit parameter to the slurm command.

### PR DESCRIPTION
**Pull request by AlbertMitjans**

### CODE REVIEW

**Comment by visagim** [comment]
I take it there are no tests for this?

**Review by visagim — DISMISSED** [review]
since we don't need to add tests it's good to go

**Comment by AlbertMitjans** [comment]
> since we don't need to add tests it's good to go

We do need to add tests! My bad 😢 

I added them! Can you take a look?

**Review by visagim — APPROVED** [review]
cool! good to go

**Pull request merged**
