### PR TITLE
Qhc 802 update qblox cluster firmware to 092 latest

### PR DESCRIPTION
**Pull request by jjmartinezQT**
This PR updates the version of qblox-instruments to latest and changes all references to the QcmQrm to the new generic Module as qblox has made this changes in the library.

### CODE REVIEW

**Review by DZPM — APPROVED** [review]
LGTM :+1:

**Review by fedonman — CHANGES_REQUESTED** [review]
Everything looks good, except the missing changelog entry. 💯 

FYI: In https://github.com/qilimanjaro-tech/qililab/pull/834 I am renaming everything to have a consistent naming, for devices this is `VendorInstrumentDevice`, so for qblox module the name will be `QbloxModuleDevice`.

**Comment by jjmartinezQT** [comment]
> Also, deprecations need to be fixed. I found the following, we should do some tests with oscilloscope before merging, just to be sure:
> 
> All deprecations: https://docs.qblox.com/en/main/getting_started/deprecated.html#deprecated
> 
> https://docs.qblox.com/en/main/getting_started/whats_new.html#deprecations image

Will work on these. I has been talking to Adrián on how to test this on the oscilloscope as we will need to do special setup for some of the cluster modules.

**Review by fedonman — APPROVED** [review]
awesome 💯 💯

**Pull request merged**
